# Generated by Django 4.2.7 on 2026-03-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_parent_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
