# Generated by Django 4.2.7 on 2026-03-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'ordering': ['display_order', 'attribute__name']},
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='menu.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='value',
        ),
    ]
