# Generated by Django 4.2.7 on 2026-03-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_attribute_alter_categoryattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='menu.attribute'),
        ),
    ]
